### ISSUE TITLE
Checkout progress indicator

### ISSUE THREAD

**Issue by natwallbank** [anth12/ReVersion#17]
The notification upon completion of checkout is really useful but it would also be good to see an indication of progress throughout the checkout process, as this can take quite a while.

**Comment by anth12** [comment]
I'm not sure showing the total progress is possible as the total repo size needs to be known in advance. Using the SvnClient Progress event will allow a total transfer size update however.

**Comment by anth12** [comment]
Added total transfer size in 4f50bc44614bafd6134bd5966c83e7022a65a911

**Comment by anth12** [comment]
Progress bar added in 3451fcf5a4147e3732f7eb91b10de9ac183b12f3. 

To calculate the repo size a separate thread executes a PS command:
`([xml](svn list --xml --recursive {{SVN_PATH}})).lists.list.entry | measure -sum size`

Release 1.2.0.2

**Comment by natwallbank** [comment]
Nice work!
